overrides:
  vite-plugin-importer>babel-plugin-import: ^1.13.8

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  oxc-resolver: true
  unrs-resolver: true
  '@magicdawn/eslint-config': true
allowedDeprecatedVersions:
  axios-userscript-adapter: '0'

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@magicdawn/*'
  - '@mgdn/*'
  - '@tanstack/*hotkeys'
  - '@types/*'
  - '@typescript/native-preview'
  - unocss-merge
  - fast-sort-lens
  - antd
  - react
  - react-dom
  - typescript
