overrides:
  vite-plugin-importer>babel-plugin-import: ^1.13.8

allowedDeprecatedVersions:
  axios-userscript-adapter: '0'

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@magicdawn/*'
  - '@mgdn/*'
  - unocss-merge
  - antd
  - react
  - react-dom
  - '@types/*'

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - oxc-resolver
  - unrs-resolver
