overrides:
  vite-plugin-importer>babel-plugin-import: ^1.13.8
  # self published version of https://github.com/unocss/unocss/pull/4801
  '@unocss/eslint-plugin': 'npm:@magicdawn/unocss__eslint-plugin@latest'

allowedDeprecatedVersions:
  axios-userscript-adapter: '0'

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@swc/core'
  - core-js-pure
  - esbuild
  - unrs-resolver
