overrides:
  vite-plugin-importer>babel-plugin-import: ^1.13.8
  '@unocss/eslint-plugin': npm:@magicdawn/unocss__eslint-plugin@dev

allowedDeprecatedVersions:
  axios-userscript-adapter: '0'

enableGlobalVirtualStore: true

configDependencies:
  '@pnpm/plugin-esm-node-path': 0.1.2+sha512-KzcFbJpNJHRZ60GpXmc6CoBX/zjy+fKEf/OOYdRbAlxV/Kf/f6pDNUDIVTQU8a5DHt6ODXq5mndwJPlryqMj1A==

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@swc/core'
  - core-js-pure
  - esbuild
  - unrs-resolver
