overrides:
  vite-plugin-importer>babel-plugin-import: ^1.13.8

allowedDeprecatedVersions:
  axios-userscript-adapter: '0'

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - oxc-resolver
  - unrs-resolver

minimumReleaseAge: 2880
