overrides:
  vite-plugin-importer>babel-plugin-import: ^1.13.8
  # https://github.com/unocss/unocss/pull/4801
  # '@unocss/eslint-plugin': file://../unocss/packages-integrations/eslint-plugin/unocss-eslint-plugin-66.3.3.tgz
  '@unocss/eslint-plugin': npm:@magicdawn/unocss__eslint-plugin@dev

allowedDeprecatedVersions:
  axios-userscript-adapter: '0'

# enableGlobalVirtualStore: true
# configDependencies:
#   '@pnpm/plugin-esm-node-path': 0.1.2+sha512-KzcFbJpNJHRZ60GpXmc6CoBX/zjy+fKEf/OOYdRbAlxV/Kf/f6pDNUDIVTQU8a5DHt6ODXq5mndwJPlryqMj1A==

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - unrs-resolver
