overrides:
  vite-plugin-importer>babel-plugin-import: ^1.13.8
  # local build of https://github.com/unocss/unocss/pull/4801
  '@unocss/eslint-plugin': file://./patches/unocss-eslint-plugin-66.3.2.tgz
allowedDeprecatedVersions:
  axios-userscript-adapter: '0'

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@swc/core'
  - core-js-pure
  - esbuild
  - unrs-resolver
