// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export namespace ipad {
  export interface AppRecommendJson {
    code: number
    message: string
    ttl: number
    data: Data
  }

  export interface Data {
    config: Config
    interest_choose: null
    items: AppRecItem[]
  }

  export interface Config {
    column: number
    autoplay_card: number
    feed_clean_abtest: number
    inline: Inline
    home_transfer_test: number
    auto_refresh_time: number
    show_inline_danmaku: number
    toast: ToastClass
    ipad_hd_abtest: number
    is_back_to_homepage: boolean
    enable_rcmd_guide: boolean
    auto_refresh_time_by_appear: number
    auto_refresh_time_by_active: number
    trigger_loadmore_left_line_num: number
    history_cache_size: number
    visible_area: number
    card_density_exp: number
    small_cover_wh_ratio: number
    space_enlarge_exp: number
    story_mode_v2_guide_exp: number
    exposure_duration_start_ratio: number
    exposure_duration_end_ratio: number
    exposure_duration_min_ms: number
    rcmd_label_mng_entrance: number
  }

  export interface Inline {
    play_strategy: number
    play_top_ratio: number
    play_bottom_ratio: number
    play_ratio: number
  }

  export interface ToastClass {}

  export interface AppRecItem {
    card_type: CardType
    card_goto: Goto
    goto: Goto
    param: string
    bvid?: string
    cover: string
    cover_badge?: string
    title: string
    uri: string
    three_point: ThreePoint
    args: Args
    player_args?: PlayerArgs
    idx: number
    mask?: Mask
    three_point_v2: ThreePointV2[]
    track_id: string
    report_flow_data?: string
    avatar?: Avatar
    cover_left_text_1?: string
    cover_left_text_2?: string
    cover_left_text_3?: string
    desc: string
    can_play: number
    cover_right_text: string
    cover_left_icon_1?: number
    cover_left_icon_2?: number
    cover_left_icon_3?: number
    official_icon?: number
    ad_info?: AdInfo
    top_rcmd_reason?: string
    top_rcmd_reason_style?: TopRcmdReasonStyle
    bottom_rcmd_reason?: string
    bottom_rcmd_reason_style?: TopRcmdReasonStyle
  }

  export interface AdInfo {
    resource: number
    source: number
    request_id: string
    index: number
    is_ad_loc: boolean
    card_index: number
    client_ip: string
  }

  export interface Args {
    up_id: number
    up_name: string
    aid: number
    ip_id: number
  }

  export interface Avatar {
    cover: string
    uri: string
    event: AvatarEvent
    event_v2: AvatarEventV2
    up_id: number
    text?: string
  }

  export enum AvatarEvent {
    UpClick = 'up_click',
  }

  export enum AvatarEventV2 {
    UpClick = 'up-click',
  }

  export type Goto = 'av' | 'ad_av' | 'picture' | 'bangumi' | 'live' | 'banner' | (string & {})

  export enum CardType {
    CMV1 = 'cm_v1',
    LargeCoverV1 = 'large_cover_v1',
  }

  export interface Mask {
    avatar: Avatar
    button: Button
  }

  export interface Button {
    text: Text
    param: string
    event: ButtonEvent
    type: number
    event_v2: ButtonEventV2
    selected?: number
  }

  export enum ButtonEvent {
    UpFollow = 'up_follow',
  }

  export enum ButtonEventV2 {
    UpFollow = 'up-follow',
  }

  export enum Text {
    关注 = '+ 关注',
  }

  export interface PlayerArgs {
    aid: number
    cid: number
    type: Goto
    duration: number
  }

  export interface ThreePoint {
    dislike_reasons: DislikeReason[]
    feedbacks?: DislikeReason[]
    watch_later?: number
  }

  export interface DislikeReason {
    id: number
    name: string
    toast: ToastEnum
  }

  export enum ToastEnum {
    将优化首页此类内容 = '将优化首页此类内容',
    将减少相似内容推荐 = '将减少相似内容推荐',
  }

  export interface ThreePointV2 {
    title?: Title
    type: Type
    icon?: string
    subtitle?: Subtitle
    reasons?: DislikeReason[]
  }

  export enum Subtitle {
    选择后将优化首页此类内容 = '(选择后将优化首页此类内容)',
    选择后将减少相似内容推荐 = '(选择后将减少相似内容推荐)',
  }

  export enum Title {
    反馈 = '反馈',
    我不想看 = '我不想看',
    添加至稍后再看 = '添加至稍后再看',
  }

  export enum Type {
    Dislike = 'dislike',
    Feedback = 'feedback',
    Watchlater = 'watch_later',
  }

  export interface TopRcmdReasonStyle {
    text: string
    text_color: string
    bg_color: string
    border_color: string
    text_color_night: string
    bg_color_night: string
    border_color_night: string
    bg_style: number
  }
}
