// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

import type { ModuleAuthor } from './module_author'
import type { ModuleDynamic__Additional } from './module_dynamic.additional'
import type { ModuleDynamic__Major } from './module_dynamic.major'

export interface DynamicFeedJson {
  code: number
  message: string
  ttl: number
  data: Data
}

export interface Data {
  has_more: boolean
  items: DynamicFeedItem[]
  offset: string
  update_baseline: string
  update_num: number
}

export interface DynamicFeedItem {
  basic: Basic
  id_str: string
  modules: DynamicFeedItemModules
  type: string
  visible: boolean
  orig?: DynamicFeedItem
}

export interface Basic {
  comment_id_str: string
  comment_type: number
  like_icon: LikeIcon
  rid_str: string
  jump_url?: string
}

export interface LikeIcon {
  action_url: string
  end_url: string
  id: number
  start_url: string
}

export interface DynamicFeedItemModules {
  module_author: ModuleAuthor
  module_dynamic: PurpleModuleDynamic
  module_more: ModuleMore
  module_stat: ModuleStat
}

export interface ContainerSize {
  height: number
  width: number
}

export interface PurpleFallbackLayers {
  is_critical_group: boolean
  layers: PurpleLayer[]
}

export interface PurpleLayer {
  general_spec: GeneralSpec
  layer_config: PurpleLayerConfig
  resource: Resource
  visible: boolean
}

export interface GeneralSpec {
  pos_spec: PosSpec
  render_spec: RenderSpec
  size_spec: ContainerSize
}

export interface PosSpec {
  axis_x: number
  axis_y: number
  coordinate_pos: number
}

export interface RenderSpec {
  opacity: number
}

export interface PurpleLayerConfig {
  is_critical?: boolean
  tags: PurpleTags
}

export interface PurpleTags {
  AVATAR_LAYER?: AvatarLayer
  GENERAL_CFG?: PurpleGENERALCFG
  ICON_LAYER?: AvatarLayer
  PENDENT_LAYER?: AvatarLayer
}

export interface AvatarLayer {}

export interface PurpleGENERALCFG {
  config_type: number
  general_config: PurpleGeneralConfig
}

export interface PurpleGeneralConfig {
  web_css_style: PurpleWebCSSStyle
}

export interface PurpleWebCSSStyle {
  'borderRadius': string
  'background-color'?: string
  'border'?: string
  'boxSizing'?: string
}

export interface Resource {
  res_image: ResImage
  res_type: number
}

export interface ResImage {
  image_src: ImageSrc
}

export interface ImageSrc {
  placeholder?: number
  remote?: Remote
  src_type: number
  local?: number
}

export interface Remote {
  bfs_style: string
  url: string
}

export interface Decorate {
  card_url: string
  fan: Fan
  id: number
  jump_url: string
  name: string
  type: number
}

export interface Fan {
  color: string
  color_format: ColorFormat | null
  is_fan: boolean
  num_prefix: string
  num_str: string
  number: number
}

export interface ColorFormat {
  colors: string[]
  end_point: string
  gradients: number[]
  start_point: string
}

export interface OfficialVerify {
  desc: string
  type: number
}

export interface Pendant {
  expire: number
  image: string
  image_enhance: string
  image_enhance_frame: string
  n_pid: number
  name: string
  pid: number
}

export interface Vip {
  avatar_subscript: number
  avatar_subscript_url: string
  due_date: number
  label: LabelClass
  nickname_color: string
  status: number
  theme_type: number
  type: number
}

export interface LabelClass {
  bg_color: string
  bg_style: number
  border_color: string
  img_label_uri_hans: string
  img_label_uri_hans_static: string
  img_label_uri_hant: string
  img_label_uri_hant_static: string
  label_theme: string
  path: string
  text: string
  text_color: string
  use_img_label: boolean
}

export interface PurpleModuleDynamic {
  major?: ModuleDynamic__Major
  additional?: ModuleDynamic__Additional
  desc?: Desc
  topic?: Topic
}

export interface Desc {
  rich_text_nodes: Rich[]
  text: string
}

export interface Rich {
  orig_text: string
  text: string
  type: RichTextNodeType
  jump_url?: string
}

export enum RichTextNodeType {
  RichTextNodeTypeText = 'RICH_TEXT_NODE_TYPE_TEXT',
  RichTextNodeTypeTopic = 'RICH_TEXT_NODE_TYPE_TOPIC',
}

export interface Badge {
  bg_color: string
  color: string
  icon_url?: null
  text: string
}

export interface Stat {
  danmaku: string
  play: string
}

export interface Topic {
  id: number
  jump_url: string
  name: string
}

export interface ModuleMore {
  three_point_items: ThreePointItem[]
}

export interface ThreePointItem {
  label: LabelEnum
  type: ThreePointItemType
}

export enum LabelEnum {
  举报 = '举报',
  取消关注 = '取消关注',
}

export enum ThreePointItemType {
  ThreePointFollowing = 'THREE_POINT_FOLLOWING',
  ThreePointReport = 'THREE_POINT_REPORT',
}

export interface ModuleStat {
  comment: Comment
  forward: Forward
  like: Like
}

export interface Comment {
  count: number
  forbidden: boolean
  hidden?: boolean
}

export interface Forward {
  count: number
  forbidden: boolean
}

export interface Like {
  count: number
  forbidden: boolean
  status: boolean
}
