import type { IRankTab } from './rank-tab'

// persist at 2025-05-09 from https://www.bilibili.com/v/popular/rank/all
export const STATIC_RANK_TABS: IRankTab[] = [
  {
    tid: 0,
    name: '全部',
    slug: 'all',
    season_type: 0,
    type: 'all',
  },
  {
    tid: 0,
    name: '番剧',
    slug: 'anime',
    season_type: 1,
    type: 'anime',
  },
  {
    tid: 0,
    name: '国创',
    slug: 'guochuang',
    season_type: 4,
    type: 'guochuang',
  },
  {
    tid: 0,
    name: '纪录片',
    slug: 'documentary',
    season_type: 3,
    type: 'documentary',
  },
  {
    tid: 0,
    name: '电影',
    slug: 'movie',
    season_type: 2,
    type: 'movie',
  },
  {
    tid: 0,
    name: '电视剧',
    slug: 'tv',
    season_type: 5,
    type: 'tv',
  },
  {
    tid: 0,
    name: '综艺',
    slug: 'variety',
    season_type: 7,
    type: 'variety',
  },
  {
    tid: 1005,
    name: '动画',
    slug: 'douga',
    season_type: 0,
    type: 'douga',
  },
  {
    tid: 1008,
    name: '游戏',
    slug: 'game',
    season_type: 0,
    type: 'game',
  },
  {
    tid: 1007,
    name: '鬼畜',
    slug: 'kichiku',
    season_type: 0,
    type: 'kichiku',
  },
  {
    tid: 1003,
    name: '音乐',
    slug: 'music',
    season_type: 0,
    type: 'music',
  },
  {
    tid: 1004,
    name: '舞蹈',
    slug: 'dance',
    season_type: 0,
    type: 'dance',
  },
  {
    tid: 1001,
    name: '影视',
    slug: 'cinephile',
    season_type: 0,
    type: 'cinephile',
  },
  {
    tid: 1002,
    name: '娱乐',
    slug: 'ent',
    season_type: 0,
    type: 'ent',
  },
  {
    tid: 1010,
    name: '知识',
    slug: 'knowledge',
    season_type: 0,
    type: 'knowledge',
  },
  {
    tid: 1012,
    name: '科技数码',
    slug: 'tech',
    season_type: 0,
    type: 'tech',
  },
  {
    tid: 1020,
    name: '美食',
    slug: 'food',
    season_type: 0,
    type: 'food',
  },
  {
    tid: 1013,
    name: '汽车',
    slug: 'car',
    season_type: 0,
    type: 'car',
  },
  {
    tid: 1014,
    name: '时尚美妆',
    slug: 'fashion',
    season_type: 0,
    type: 'fashion',
  },
  {
    tid: 1018,
    name: '体育运动',
    slug: 'sports',
    season_type: 0,
    type: 'sports',
  },
  {
    tid: 1024,
    name: '动物',
    slug: 'animal',
    season_type: 0,
    type: 'animal',
  },
]
