name: CI

on:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}
  # 很烦: 通知无法关掉
  # cancel-in-progress: true

jobs:
  ghd:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      describe: ${{ steps.ghd.outputs.describe }}
      tag: ${{ steps.ghd.outputs.tag }}
      distance: ${{ steps.ghd.outputs.distance }}
      sha: ${{ steps.ghd.outputs.sha }}
    steps:
      - name: Git describe
        id: ghd
        uses: proudust/gh-describe@v2

  test-and-build:
    runs-on: ubuntu-latest

    # git describe
    needs: ghd
    env:
      RELEASE_NIGHTLY: 'true'
      GHD_DESCRIBE: ${{ needs.ghd.outputs.describe }}
      GHD_TAG: ${{ needs.ghd.outputs.tag }}
      GHD_DISTANCE: ${{ needs.ghd.outputs.distance }}
      GHD_SHA: ${{ needs.ghd.outputs.sha }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # install deps
      - run: pnpm install --frozen-lockfile

      # turbo cache
      - uses: actions/cache@v4
        with:
          path: node_modules/.cache/turbo
          key: turbo-cache-${{ runner.os }}

      # code check
      - run: pnpm turbo build:scss _typecheck

      # test
      - run: pnpm test

      # run knip report
      - run: pnpm knip
        continue-on-error: true

      # build
      - run: pnpm build:real-build
        env:
          MINIFY: 'false'
      - run: pnpm build:real-build
        env:
          MINIFY: 'true'

      # prepare
      - run: cp README.md CHANGELOG.md ./dist

      # commit to release-nightly branch
      - uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: release-nightly
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
