name: release

on:
  push:
    tags:
      - 'v0*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      RELEASE: 'true'
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v3
        with: { version: 8 }

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      # install deps
      - run: pnpm install --frozen-lockfile

      # turbo cache
      - uses: actions/cache@v3
        with:
          path: node_modules/.cache/turbo
          key: turbo-cache-${{ runner.os }}

      # code check
      - run: pnpm turbo build:scss typecheck

      # test
      - run: pnpm test

      # build for greasyfork
      - run: pnpm build:real-build
        env:
          MINIFY: 'false'

      # build minified version
      - run: pnpm build:real-build
        env:
          MINIFY: 'true'

      # prepare
      - run: cp README.md CHANGELOG.md ./dist

      # commit to release branch
      - uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: release
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # webhook not working when orphan commit
          # greasyfork webhook 依赖 modified: [], 需要包含 xxx.user.js
          # https://github.com/YDX-2147483647/BIT-enhanced/issues/4#issuecomment-1590620027
          force_orphan: false
